show_command_form:
    path:     /
    defaults: { _controller: AppBundle:Command:home }
    methods: [GET]

submit_command_form:
    path:     /submit
    defaults: { _controller: AppBundle:Command:postCommand }
    methods: [POST]

process_payment:
    path: /payment
    defaults: {_controller: AppBundle:Command:processPayment }
    methods: [POST]

