command_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:home }

command_visitorform:
    path:     /order/validate
    defaults: { _controller: AppBundle:Default:postCommand }

