services:
#    command.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    command.form.type:
          class: AppBundle\Form\Type\CommandType
          calls:
                - [setRouter, ['@router']]
          tags:
                - { name: form.type }
    command.factory:
        class: AppBundle\Entity\CommandFactory
        calls:
          - [ setVisitorFactory, ['@visitor.factory']]

    visitor.factory:
        class: AppBundle\Entity\VisitorFactory

    command.repository:
            class: AppBundle\Repository\CommandRepository
            parent: doctrine.orm.entity_manager

